apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: backend
  namespace: kmesh-demo
  labels:
    istio.io/use-waypoint: waypoint # svc 接入 L7 waypoint 代理
spec:
  hosts:
  - backend
  http:
  - headers:
      request:
        set:
          test: "true"
    route:
    - destination:
        host: backend-v2.kmesh-demo.svc.cluster.local
      weight: 10
    - destination:
        host: backend-v1.kmesh-demo.svc.cluster.local
      weight: 90
