apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmesh
  labels:
    app: kmesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmesh
subjects:
- kind: ServiceAccount
  name: kmesh
  namespace: kmesh-system
