apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  revision: 1-24
  meshConfig:
    enableTracing: true
#   image:
#     imageType: distroless
  components:
    pilot:
      k8s:
        env:
        - name: "PILOT_ENABLE_AMBIENT"
          value: "true"
