apiVersion: v1
kind: Namespace
metadata:
  name: kmesh-demo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reconciler
  namespace: kmesh-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reconciler
  namespace: kmesh-demo
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reconciler
  namespace: kmesh-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reconciler
subjects:
  - kind: ServiceAccount
    name: reconciler
    namespace: kmesh-demo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kmesh-demo
  namespace: kmesh-demo
